name: 'Amazon ECS "Run Task" Action for GitHub Actions'
description: 'Runs an Amazon ECS task'
branding:
  icon: 'cloud'
  color: 'orange'
inputs:
  task-definition:
    description: 'The filename (<file>.json) of the ECS task definition'
    required: true
  task-definition-arn:
    description: 'The ECS task definition ARN'
  cluster:
    description: "The name of the ECS cluster. Will default to the 'default' cluster"
    required: true
  count:
    description: "The count of tasks to run. Will default to 1"
    required: true
  security-groups:
    description: "The array of security groups to set in the network configuration. Will default to an empty array."
    required: false
  subnets:
    description: "The array of subnets to set in the network configuration. Will default to an empty array."
    required: false
  started-by:
    description: "The value of the task started-by"
    required: false
  wait-for-finish:
    description: "Whether to wait for tasks to reach stopped state. Will default to not waiting"
    required: false
  wait-for-minutes:
    description: 'How long to wait for the task reach stopped state, in minutes (default: 30 minutes, max: 6 hours).'
    required: false
outputs:
  task-definition-arn:
    description: 'The ARN of the registered ECS task definition'
  task-arn:
    description: 'The ARN of the ECS task'
runs:
  using: 'node16'
  main: 'dist/index.js'
